// Code generated by smithy-go-codegen DO NOT EDIT.

package backupgateway

import (
	"bytes"
	"context"
	"fmt"
	"github.com/aws/aws-sdk-go-v2/service/backupgateway/types"
	smithy "github.com/aws/smithy-go"
	smithycbor "github.com/aws/smithy-go/encoding/cbor"
	"github.com/aws/smithy-go/middleware"
	"github.com/aws/smithy-go/tracing"
	smithyhttp "github.com/aws/smithy-go/transport/http"
	"net/http"
)

type smithyRpcv2cbor_serializeOpAssociateGatewayToServer struct {
}

func (*smithyRpcv2cbor_serializeOpAssociateGatewayToServer) ID() string {
	return "OperationSerializer"
}

func (m *smithyRpcv2cbor_serializeOpAssociateGatewayToServer) HandleSerialize(ctx context.Context, in middleware.SerializeInput, next middleware.SerializeHandler) (
	out middleware.SerializeOutput, metadata middleware.Metadata, err error,
) {
	_, span := tracing.StartSpan(ctx, "OperationSerializer")
	endTimer := startMetricTimer(ctx, "client.call.serialization_duration")
	defer endTimer()
	defer span.End()
	input, ok := in.Parameters.(*AssociateGatewayToServerInput)
	if !ok {
		return out, metadata, fmt.Errorf("unexpected input type %T", in.Parameters)
	}
	_ = input

	req, ok := in.Request.(*smithyhttp.Request)
	if !ok {
		return out, metadata, fmt.Errorf("unexpected transport type %T", in.Request)
	}

	req.Method = http.MethodPost
	req.URL.Path = "/service/BackupOnPremises_v20210101/operation/AssociateGatewayToServer"
	req.Header.Set("smithy-protocol", "rpc-v2-cbor")

	req.Header.Set("Content-Type", "application/cbor")
	req.Header.Set("Accept", "application/cbor")

	cv, err := serializeCBOR_AssociateGatewayToServerInput(input)
	if err != nil {
		return out, metadata, &smithy.SerializationError{Err: err}
	}

	payload := bytes.NewReader(smithycbor.Encode(cv))
	if req, err = req.SetStream(payload); err != nil {
		return out, metadata, &smithy.SerializationError{Err: err}
	}

	in.Request = req

	endTimer()
	span.End()

	return next.HandleSerialize(ctx, in)
}

type smithyRpcv2cbor_serializeOpCreateGateway struct {
}

func (*smithyRpcv2cbor_serializeOpCreateGateway) ID() string {
	return "OperationSerializer"
}

func (m *smithyRpcv2cbor_serializeOpCreateGateway) HandleSerialize(ctx context.Context, in middleware.SerializeInput, next middleware.SerializeHandler) (
	out middleware.SerializeOutput, metadata middleware.Metadata, err error,
) {
	_, span := tracing.StartSpan(ctx, "OperationSerializer")
	endTimer := startMetricTimer(ctx, "client.call.serialization_duration")
	defer endTimer()
	defer span.End()
	input, ok := in.Parameters.(*CreateGatewayInput)
	if !ok {
		return out, metadata, fmt.Errorf("unexpected input type %T", in.Parameters)
	}
	_ = input

	req, ok := in.Request.(*smithyhttp.Request)
	if !ok {
		return out, metadata, fmt.Errorf("unexpected transport type %T", in.Request)
	}

	req.Method = http.MethodPost
	req.URL.Path = "/service/BackupOnPremises_v20210101/operation/CreateGateway"
	req.Header.Set("smithy-protocol", "rpc-v2-cbor")

	req.Header.Set("Content-Type", "application/cbor")
	req.Header.Set("Accept", "application/cbor")

	cv, err := serializeCBOR_CreateGatewayInput(input)
	if err != nil {
		return out, metadata, &smithy.SerializationError{Err: err}
	}

	payload := bytes.NewReader(smithycbor.Encode(cv))
	if req, err = req.SetStream(payload); err != nil {
		return out, metadata, &smithy.SerializationError{Err: err}
	}

	in.Request = req

	endTimer()
	span.End()

	return next.HandleSerialize(ctx, in)
}

type smithyRpcv2cbor_serializeOpDeleteGateway struct {
}

func (*smithyRpcv2cbor_serializeOpDeleteGateway) ID() string {
	return "OperationSerializer"
}

func (m *smithyRpcv2cbor_serializeOpDeleteGateway) HandleSerialize(ctx context.Context, in middleware.SerializeInput, next middleware.SerializeHandler) (
	out middleware.SerializeOutput, metadata middleware.Metadata, err error,
) {
	_, span := tracing.StartSpan(ctx, "OperationSerializer")
	endTimer := startMetricTimer(ctx, "client.call.serialization_duration")
	defer endTimer()
	defer span.End()
	input, ok := in.Parameters.(*DeleteGatewayInput)
	if !ok {
		return out, metadata, fmt.Errorf("unexpected input type %T", in.Parameters)
	}
	_ = input

	req, ok := in.Request.(*smithyhttp.Request)
	if !ok {
		return out, metadata, fmt.Errorf("unexpected transport type %T", in.Request)
	}

	req.Method = http.MethodPost
	req.URL.Path = "/service/BackupOnPremises_v20210101/operation/DeleteGateway"
	req.Header.Set("smithy-protocol", "rpc-v2-cbor")

	req.Header.Set("Content-Type", "application/cbor")
	req.Header.Set("Accept", "application/cbor")

	cv, err := serializeCBOR_DeleteGatewayInput(input)
	if err != nil {
		return out, metadata, &smithy.SerializationError{Err: err}
	}

	payload := bytes.NewReader(smithycbor.Encode(cv))
	if req, err = req.SetStream(payload); err != nil {
		return out, metadata, &smithy.SerializationError{Err: err}
	}

	in.Request = req

	endTimer()
	span.End()

	return next.HandleSerialize(ctx, in)
}

type smithyRpcv2cbor_serializeOpDeleteHypervisor struct {
}

func (*smithyRpcv2cbor_serializeOpDeleteHypervisor) ID() string {
	return "OperationSerializer"
}

func (m *smithyRpcv2cbor_serializeOpDeleteHypervisor) HandleSerialize(ctx context.Context, in middleware.SerializeInput, next middleware.SerializeHandler) (
	out middleware.SerializeOutput, metadata middleware.Metadata, err error,
) {
	_, span := tracing.StartSpan(ctx, "OperationSerializer")
	endTimer := startMetricTimer(ctx, "client.call.serialization_duration")
	defer endTimer()
	defer span.End()
	input, ok := in.Parameters.(*DeleteHypervisorInput)
	if !ok {
		return out, metadata, fmt.Errorf("unexpected input type %T", in.Parameters)
	}
	_ = input

	req, ok := in.Request.(*smithyhttp.Request)
	if !ok {
		return out, metadata, fmt.Errorf("unexpected transport type %T", in.Request)
	}

	req.Method = http.MethodPost
	req.URL.Path = "/service/BackupOnPremises_v20210101/operation/DeleteHypervisor"
	req.Header.Set("smithy-protocol", "rpc-v2-cbor")

	req.Header.Set("Content-Type", "application/cbor")
	req.Header.Set("Accept", "application/cbor")

	cv, err := serializeCBOR_DeleteHypervisorInput(input)
	if err != nil {
		return out, metadata, &smithy.SerializationError{Err: err}
	}

	payload := bytes.NewReader(smithycbor.Encode(cv))
	if req, err = req.SetStream(payload); err != nil {
		return out, metadata, &smithy.SerializationError{Err: err}
	}

	in.Request = req

	endTimer()
	span.End()

	return next.HandleSerialize(ctx, in)
}

type smithyRpcv2cbor_serializeOpDisassociateGatewayFromServer struct {
}

func (*smithyRpcv2cbor_serializeOpDisassociateGatewayFromServer) ID() string {
	return "OperationSerializer"
}

func (m *smithyRpcv2cbor_serializeOpDisassociateGatewayFromServer) HandleSerialize(ctx context.Context, in middleware.SerializeInput, next middleware.SerializeHandler) (
	out middleware.SerializeOutput, metadata middleware.Metadata, err error,
) {
	_, span := tracing.StartSpan(ctx, "OperationSerializer")
	endTimer := startMetricTimer(ctx, "client.call.serialization_duration")
	defer endTimer()
	defer span.End()
	input, ok := in.Parameters.(*DisassociateGatewayFromServerInput)
	if !ok {
		return out, metadata, fmt.Errorf("unexpected input type %T", in.Parameters)
	}
	_ = input

	req, ok := in.Request.(*smithyhttp.Request)
	if !ok {
		return out, metadata, fmt.Errorf("unexpected transport type %T", in.Request)
	}

	req.Method = http.MethodPost
	req.URL.Path = "/service/BackupOnPremises_v20210101/operation/DisassociateGatewayFromServer"
	req.Header.Set("smithy-protocol", "rpc-v2-cbor")

	req.Header.Set("Content-Type", "application/cbor")
	req.Header.Set("Accept", "application/cbor")

	cv, err := serializeCBOR_DisassociateGatewayFromServerInput(input)
	if err != nil {
		return out, metadata, &smithy.SerializationError{Err: err}
	}

	payload := bytes.NewReader(smithycbor.Encode(cv))
	if req, err = req.SetStream(payload); err != nil {
		return out, metadata, &smithy.SerializationError{Err: err}
	}

	in.Request = req

	endTimer()
	span.End()

	return next.HandleSerialize(ctx, in)
}

type smithyRpcv2cbor_serializeOpGetBandwidthRateLimitSchedule struct {
}

func (*smithyRpcv2cbor_serializeOpGetBandwidthRateLimitSchedule) ID() string {
	return "OperationSerializer"
}

func (m *smithyRpcv2cbor_serializeOpGetBandwidthRateLimitSchedule) HandleSerialize(ctx context.Context, in middleware.SerializeInput, next middleware.SerializeHandler) (
	out middleware.SerializeOutput, metadata middleware.Metadata, err error,
) {
	_, span := tracing.StartSpan(ctx, "OperationSerializer")
	endTimer := startMetricTimer(ctx, "client.call.serialization_duration")
	defer endTimer()
	defer span.End()
	input, ok := in.Parameters.(*GetBandwidthRateLimitScheduleInput)
	if !ok {
		return out, metadata, fmt.Errorf("unexpected input type %T", in.Parameters)
	}
	_ = input

	req, ok := in.Request.(*smithyhttp.Request)
	if !ok {
		return out, metadata, fmt.Errorf("unexpected transport type %T", in.Request)
	}

	req.Method = http.MethodPost
	req.URL.Path = "/service/BackupOnPremises_v20210101/operation/GetBandwidthRateLimitSchedule"
	req.Header.Set("smithy-protocol", "rpc-v2-cbor")

	req.Header.Set("Content-Type", "application/cbor")
	req.Header.Set("Accept", "application/cbor")

	cv, err := serializeCBOR_GetBandwidthRateLimitScheduleInput(input)
	if err != nil {
		return out, metadata, &smithy.SerializationError{Err: err}
	}

	payload := bytes.NewReader(smithycbor.Encode(cv))
	if req, err = req.SetStream(payload); err != nil {
		return out, metadata, &smithy.SerializationError{Err: err}
	}

	in.Request = req

	endTimer()
	span.End()

	return next.HandleSerialize(ctx, in)
}

type smithyRpcv2cbor_serializeOpGetGateway struct {
}

func (*smithyRpcv2cbor_serializeOpGetGateway) ID() string {
	return "OperationSerializer"
}

func (m *smithyRpcv2cbor_serializeOpGetGateway) HandleSerialize(ctx context.Context, in middleware.SerializeInput, next middleware.SerializeHandler) (
	out middleware.SerializeOutput, metadata middleware.Metadata, err error,
) {
	_, span := tracing.StartSpan(ctx, "OperationSerializer")
	endTimer := startMetricTimer(ctx, "client.call.serialization_duration")
	defer endTimer()
	defer span.End()
	input, ok := in.Parameters.(*GetGatewayInput)
	if !ok {
		return out, metadata, fmt.Errorf("unexpected input type %T", in.Parameters)
	}
	_ = input

	req, ok := in.Request.(*smithyhttp.Request)
	if !ok {
		return out, metadata, fmt.Errorf("unexpected transport type %T", in.Request)
	}

	req.Method = http.MethodPost
	req.URL.Path = "/service/BackupOnPremises_v20210101/operation/GetGateway"
	req.Header.Set("smithy-protocol", "rpc-v2-cbor")

	req.Header.Set("Content-Type", "application/cbor")
	req.Header.Set("Accept", "application/cbor")

	cv, err := serializeCBOR_GetGatewayInput(input)
	if err != nil {
		return out, metadata, &smithy.SerializationError{Err: err}
	}

	payload := bytes.NewReader(smithycbor.Encode(cv))
	if req, err = req.SetStream(payload); err != nil {
		return out, metadata, &smithy.SerializationError{Err: err}
	}

	in.Request = req

	endTimer()
	span.End()

	return next.HandleSerialize(ctx, in)
}

type smithyRpcv2cbor_serializeOpGetHypervisor struct {
}

func (*smithyRpcv2cbor_serializeOpGetHypervisor) ID() string {
	return "OperationSerializer"
}

func (m *smithyRpcv2cbor_serializeOpGetHypervisor) HandleSerialize(ctx context.Context, in middleware.SerializeInput, next middleware.SerializeHandler) (
	out middleware.SerializeOutput, metadata middleware.Metadata, err error,
) {
	_, span := tracing.StartSpan(ctx, "OperationSerializer")
	endTimer := startMetricTimer(ctx, "client.call.serialization_duration")
	defer endTimer()
	defer span.End()
	input, ok := in.Parameters.(*GetHypervisorInput)
	if !ok {
		return out, metadata, fmt.Errorf("unexpected input type %T", in.Parameters)
	}
	_ = input

	req, ok := in.Request.(*smithyhttp.Request)
	if !ok {
		return out, metadata, fmt.Errorf("unexpected transport type %T", in.Request)
	}

	req.Method = http.MethodPost
	req.URL.Path = "/service/BackupOnPremises_v20210101/operation/GetHypervisor"
	req.Header.Set("smithy-protocol", "rpc-v2-cbor")

	req.Header.Set("Content-Type", "application/cbor")
	req.Header.Set("Accept", "application/cbor")

	cv, err := serializeCBOR_GetHypervisorInput(input)
	if err != nil {
		return out, metadata, &smithy.SerializationError{Err: err}
	}

	payload := bytes.NewReader(smithycbor.Encode(cv))
	if req, err = req.SetStream(payload); err != nil {
		return out, metadata, &smithy.SerializationError{Err: err}
	}

	in.Request = req

	endTimer()
	span.End()

	return next.HandleSerialize(ctx, in)
}

type smithyRpcv2cbor_serializeOpGetHypervisorPropertyMappings struct {
}

func (*smithyRpcv2cbor_serializeOpGetHypervisorPropertyMappings) ID() string {
	return "OperationSerializer"
}

func (m *smithyRpcv2cbor_serializeOpGetHypervisorPropertyMappings) HandleSerialize(ctx context.Context, in middleware.SerializeInput, next middleware.SerializeHandler) (
	out middleware.SerializeOutput, metadata middleware.Metadata, err error,
) {
	_, span := tracing.StartSpan(ctx, "OperationSerializer")
	endTimer := startMetricTimer(ctx, "client.call.serialization_duration")
	defer endTimer()
	defer span.End()
	input, ok := in.Parameters.(*GetHypervisorPropertyMappingsInput)
	if !ok {
		return out, metadata, fmt.Errorf("unexpected input type %T", in.Parameters)
	}
	_ = input

	req, ok := in.Request.(*smithyhttp.Request)
	if !ok {
		return out, metadata, fmt.Errorf("unexpected transport type %T", in.Request)
	}

	req.Method = http.MethodPost
	req.URL.Path = "/service/BackupOnPremises_v20210101/operation/GetHypervisorPropertyMappings"
	req.Header.Set("smithy-protocol", "rpc-v2-cbor")

	req.Header.Set("Content-Type", "application/cbor")
	req.Header.Set("Accept", "application/cbor")

	cv, err := serializeCBOR_GetHypervisorPropertyMappingsInput(input)
	if err != nil {
		return out, metadata, &smithy.SerializationError{Err: err}
	}

	payload := bytes.NewReader(smithycbor.Encode(cv))
	if req, err = req.SetStream(payload); err != nil {
		return out, metadata, &smithy.SerializationError{Err: err}
	}

	in.Request = req

	endTimer()
	span.End()

	return next.HandleSerialize(ctx, in)
}

type smithyRpcv2cbor_serializeOpGetVirtualMachine struct {
}

func (*smithyRpcv2cbor_serializeOpGetVirtualMachine) ID() string {
	return "OperationSerializer"
}

func (m *smithyRpcv2cbor_serializeOpGetVirtualMachine) HandleSerialize(ctx context.Context, in middleware.SerializeInput, next middleware.SerializeHandler) (
	out middleware.SerializeOutput, metadata middleware.Metadata, err error,
) {
	_, span := tracing.StartSpan(ctx, "OperationSerializer")
	endTimer := startMetricTimer(ctx, "client.call.serialization_duration")
	defer endTimer()
	defer span.End()
	input, ok := in.Parameters.(*GetVirtualMachineInput)
	if !ok {
		return out, metadata, fmt.Errorf("unexpected input type %T", in.Parameters)
	}
	_ = input

	req, ok := in.Request.(*smithyhttp.Request)
	if !ok {
		return out, metadata, fmt.Errorf("unexpected transport type %T", in.Request)
	}

	req.Method = http.MethodPost
	req.URL.Path = "/service/BackupOnPremises_v20210101/operation/GetVirtualMachine"
	req.Header.Set("smithy-protocol", "rpc-v2-cbor")

	req.Header.Set("Content-Type", "application/cbor")
	req.Header.Set("Accept", "application/cbor")

	cv, err := serializeCBOR_GetVirtualMachineInput(input)
	if err != nil {
		return out, metadata, &smithy.SerializationError{Err: err}
	}

	payload := bytes.NewReader(smithycbor.Encode(cv))
	if req, err = req.SetStream(payload); err != nil {
		return out, metadata, &smithy.SerializationError{Err: err}
	}

	in.Request = req

	endTimer()
	span.End()

	return next.HandleSerialize(ctx, in)
}

type smithyRpcv2cbor_serializeOpImportHypervisorConfiguration struct {
}

func (*smithyRpcv2cbor_serializeOpImportHypervisorConfiguration) ID() string {
	return "OperationSerializer"
}

func (m *smithyRpcv2cbor_serializeOpImportHypervisorConfiguration) HandleSerialize(ctx context.Context, in middleware.SerializeInput, next middleware.SerializeHandler) (
	out middleware.SerializeOutput, metadata middleware.Metadata, err error,
) {
	_, span := tracing.StartSpan(ctx, "OperationSerializer")
	endTimer := startMetricTimer(ctx, "client.call.serialization_duration")
	defer endTimer()
	defer span.End()
	input, ok := in.Parameters.(*ImportHypervisorConfigurationInput)
	if !ok {
		return out, metadata, fmt.Errorf("unexpected input type %T", in.Parameters)
	}
	_ = input

	req, ok := in.Request.(*smithyhttp.Request)
	if !ok {
		return out, metadata, fmt.Errorf("unexpected transport type %T", in.Request)
	}

	req.Method = http.MethodPost
	req.URL.Path = "/service/BackupOnPremises_v20210101/operation/ImportHypervisorConfiguration"
	req.Header.Set("smithy-protocol", "rpc-v2-cbor")

	req.Header.Set("Content-Type", "application/cbor")
	req.Header.Set("Accept", "application/cbor")

	cv, err := serializeCBOR_ImportHypervisorConfigurationInput(input)
	if err != nil {
		return out, metadata, &smithy.SerializationError{Err: err}
	}

	payload := bytes.NewReader(smithycbor.Encode(cv))
	if req, err = req.SetStream(payload); err != nil {
		return out, metadata, &smithy.SerializationError{Err: err}
	}

	in.Request = req

	endTimer()
	span.End()

	return next.HandleSerialize(ctx, in)
}

type smithyRpcv2cbor_serializeOpListGateways struct {
}

func (*smithyRpcv2cbor_serializeOpListGateways) ID() string {
	return "OperationSerializer"
}

func (m *smithyRpcv2cbor_serializeOpListGateways) HandleSerialize(ctx context.Context, in middleware.SerializeInput, next middleware.SerializeHandler) (
	out middleware.SerializeOutput, metadata middleware.Metadata, err error,
) {
	_, span := tracing.StartSpan(ctx, "OperationSerializer")
	endTimer := startMetricTimer(ctx, "client.call.serialization_duration")
	defer endTimer()
	defer span.End()
	input, ok := in.Parameters.(*ListGatewaysInput)
	if !ok {
		return out, metadata, fmt.Errorf("unexpected input type %T", in.Parameters)
	}
	_ = input

	req, ok := in.Request.(*smithyhttp.Request)
	if !ok {
		return out, metadata, fmt.Errorf("unexpected transport type %T", in.Request)
	}

	req.Method = http.MethodPost
	req.URL.Path = "/service/BackupOnPremises_v20210101/operation/ListGateways"
	req.Header.Set("smithy-protocol", "rpc-v2-cbor")

	req.Header.Set("Content-Type", "application/cbor")
	req.Header.Set("Accept", "application/cbor")

	cv, err := serializeCBOR_ListGatewaysInput(input)
	if err != nil {
		return out, metadata, &smithy.SerializationError{Err: err}
	}

	payload := bytes.NewReader(smithycbor.Encode(cv))
	if req, err = req.SetStream(payload); err != nil {
		return out, metadata, &smithy.SerializationError{Err: err}
	}

	in.Request = req

	endTimer()
	span.End()

	return next.HandleSerialize(ctx, in)
}

type smithyRpcv2cbor_serializeOpListHypervisors struct {
}

func (*smithyRpcv2cbor_serializeOpListHypervisors) ID() string {
	return "OperationSerializer"
}

func (m *smithyRpcv2cbor_serializeOpListHypervisors) HandleSerialize(ctx context.Context, in middleware.SerializeInput, next middleware.SerializeHandler) (
	out middleware.SerializeOutput, metadata middleware.Metadata, err error,
) {
	_, span := tracing.StartSpan(ctx, "OperationSerializer")
	endTimer := startMetricTimer(ctx, "client.call.serialization_duration")
	defer endTimer()
	defer span.End()
	input, ok := in.Parameters.(*ListHypervisorsInput)
	if !ok {
		return out, metadata, fmt.Errorf("unexpected input type %T", in.Parameters)
	}
	_ = input

	req, ok := in.Request.(*smithyhttp.Request)
	if !ok {
		return out, metadata, fmt.Errorf("unexpected transport type %T", in.Request)
	}

	req.Method = http.MethodPost
	req.URL.Path = "/service/BackupOnPremises_v20210101/operation/ListHypervisors"
	req.Header.Set("smithy-protocol", "rpc-v2-cbor")

	req.Header.Set("Content-Type", "application/cbor")
	req.Header.Set("Accept", "application/cbor")

	cv, err := serializeCBOR_ListHypervisorsInput(input)
	if err != nil {
		return out, metadata, &smithy.SerializationError{Err: err}
	}

	payload := bytes.NewReader(smithycbor.Encode(cv))
	if req, err = req.SetStream(payload); err != nil {
		return out, metadata, &smithy.SerializationError{Err: err}
	}

	in.Request = req

	endTimer()
	span.End()

	return next.HandleSerialize(ctx, in)
}

type smithyRpcv2cbor_serializeOpListTagsForResource struct {
}

func (*smithyRpcv2cbor_serializeOpListTagsForResource) ID() string {
	return "OperationSerializer"
}

func (m *smithyRpcv2cbor_serializeOpListTagsForResource) HandleSerialize(ctx context.Context, in middleware.SerializeInput, next middleware.SerializeHandler) (
	out middleware.SerializeOutput, metadata middleware.Metadata, err error,
) {
	_, span := tracing.StartSpan(ctx, "OperationSerializer")
	endTimer := startMetricTimer(ctx, "client.call.serialization_duration")
	defer endTimer()
	defer span.End()
	input, ok := in.Parameters.(*ListTagsForResourceInput)
	if !ok {
		return out, metadata, fmt.Errorf("unexpected input type %T", in.Parameters)
	}
	_ = input

	req, ok := in.Request.(*smithyhttp.Request)
	if !ok {
		return out, metadata, fmt.Errorf("unexpected transport type %T", in.Request)
	}

	req.Method = http.MethodPost
	req.URL.Path = "/service/BackupOnPremises_v20210101/operation/ListTagsForResource"
	req.Header.Set("smithy-protocol", "rpc-v2-cbor")

	req.Header.Set("Content-Type", "application/cbor")
	req.Header.Set("Accept", "application/cbor")

	cv, err := serializeCBOR_ListTagsForResourceInput(input)
	if err != nil {
		return out, metadata, &smithy.SerializationError{Err: err}
	}

	payload := bytes.NewReader(smithycbor.Encode(cv))
	if req, err = req.SetStream(payload); err != nil {
		return out, metadata, &smithy.SerializationError{Err: err}
	}

	in.Request = req

	endTimer()
	span.End()

	return next.HandleSerialize(ctx, in)
}

type smithyRpcv2cbor_serializeOpListVirtualMachines struct {
}

func (*smithyRpcv2cbor_serializeOpListVirtualMachines) ID() string {
	return "OperationSerializer"
}

func (m *smithyRpcv2cbor_serializeOpListVirtualMachines) HandleSerialize(ctx context.Context, in middleware.SerializeInput, next middleware.SerializeHandler) (
	out middleware.SerializeOutput, metadata middleware.Metadata, err error,
) {
	_, span := tracing.StartSpan(ctx, "OperationSerializer")
	endTimer := startMetricTimer(ctx, "client.call.serialization_duration")
	defer endTimer()
	defer span.End()
	input, ok := in.Parameters.(*ListVirtualMachinesInput)
	if !ok {
		return out, metadata, fmt.Errorf("unexpected input type %T", in.Parameters)
	}
	_ = input

	req, ok := in.Request.(*smithyhttp.Request)
	if !ok {
		return out, metadata, fmt.Errorf("unexpected transport type %T", in.Request)
	}

	req.Method = http.MethodPost
	req.URL.Path = "/service/BackupOnPremises_v20210101/operation/ListVirtualMachines"
	req.Header.Set("smithy-protocol", "rpc-v2-cbor")

	req.Header.Set("Content-Type", "application/cbor")
	req.Header.Set("Accept", "application/cbor")

	cv, err := serializeCBOR_ListVirtualMachinesInput(input)
	if err != nil {
		return out, metadata, &smithy.SerializationError{Err: err}
	}

	payload := bytes.NewReader(smithycbor.Encode(cv))
	if req, err = req.SetStream(payload); err != nil {
		return out, metadata, &smithy.SerializationError{Err: err}
	}

	in.Request = req

	endTimer()
	span.End()

	return next.HandleSerialize(ctx, in)
}

type smithyRpcv2cbor_serializeOpPutBandwidthRateLimitSchedule struct {
}

func (*smithyRpcv2cbor_serializeOpPutBandwidthRateLimitSchedule) ID() string {
	return "OperationSerializer"
}

func (m *smithyRpcv2cbor_serializeOpPutBandwidthRateLimitSchedule) HandleSerialize(ctx context.Context, in middleware.SerializeInput, next middleware.SerializeHandler) (
	out middleware.SerializeOutput, metadata middleware.Metadata, err error,
) {
	_, span := tracing.StartSpan(ctx, "OperationSerializer")
	endTimer := startMetricTimer(ctx, "client.call.serialization_duration")
	defer endTimer()
	defer span.End()
	input, ok := in.Parameters.(*PutBandwidthRateLimitScheduleInput)
	if !ok {
		return out, metadata, fmt.Errorf("unexpected input type %T", in.Parameters)
	}
	_ = input

	req, ok := in.Request.(*smithyhttp.Request)
	if !ok {
		return out, metadata, fmt.Errorf("unexpected transport type %T", in.Request)
	}

	req.Method = http.MethodPost
	req.URL.Path = "/service/BackupOnPremises_v20210101/operation/PutBandwidthRateLimitSchedule"
	req.Header.Set("smithy-protocol", "rpc-v2-cbor")

	req.Header.Set("Content-Type", "application/cbor")
	req.Header.Set("Accept", "application/cbor")

	cv, err := serializeCBOR_PutBandwidthRateLimitScheduleInput(input)
	if err != nil {
		return out, metadata, &smithy.SerializationError{Err: err}
	}

	payload := bytes.NewReader(smithycbor.Encode(cv))
	if req, err = req.SetStream(payload); err != nil {
		return out, metadata, &smithy.SerializationError{Err: err}
	}

	in.Request = req

	endTimer()
	span.End()

	return next.HandleSerialize(ctx, in)
}

type smithyRpcv2cbor_serializeOpPutHypervisorPropertyMappings struct {
}

func (*smithyRpcv2cbor_serializeOpPutHypervisorPropertyMappings) ID() string {
	return "OperationSerializer"
}

func (m *smithyRpcv2cbor_serializeOpPutHypervisorPropertyMappings) HandleSerialize(ctx context.Context, in middleware.SerializeInput, next middleware.SerializeHandler) (
	out middleware.SerializeOutput, metadata middleware.Metadata, err error,
) {
	_, span := tracing.StartSpan(ctx, "OperationSerializer")
	endTimer := startMetricTimer(ctx, "client.call.serialization_duration")
	defer endTimer()
	defer span.End()
	input, ok := in.Parameters.(*PutHypervisorPropertyMappingsInput)
	if !ok {
		return out, metadata, fmt.Errorf("unexpected input type %T", in.Parameters)
	}
	_ = input

	req, ok := in.Request.(*smithyhttp.Request)
	if !ok {
		return out, metadata, fmt.Errorf("unexpected transport type %T", in.Request)
	}

	req.Method = http.MethodPost
	req.URL.Path = "/service/BackupOnPremises_v20210101/operation/PutHypervisorPropertyMappings"
	req.Header.Set("smithy-protocol", "rpc-v2-cbor")

	req.Header.Set("Content-Type", "application/cbor")
	req.Header.Set("Accept", "application/cbor")

	cv, err := serializeCBOR_PutHypervisorPropertyMappingsInput(input)
	if err != nil {
		return out, metadata, &smithy.SerializationError{Err: err}
	}

	payload := bytes.NewReader(smithycbor.Encode(cv))
	if req, err = req.SetStream(payload); err != nil {
		return out, metadata, &smithy.SerializationError{Err: err}
	}

	in.Request = req

	endTimer()
	span.End()

	return next.HandleSerialize(ctx, in)
}

type smithyRpcv2cbor_serializeOpPutMaintenanceStartTime struct {
}

func (*smithyRpcv2cbor_serializeOpPutMaintenanceStartTime) ID() string {
	return "OperationSerializer"
}

func (m *smithyRpcv2cbor_serializeOpPutMaintenanceStartTime) HandleSerialize(ctx context.Context, in middleware.SerializeInput, next middleware.SerializeHandler) (
	out middleware.SerializeOutput, metadata middleware.Metadata, err error,
) {
	_, span := tracing.StartSpan(ctx, "OperationSerializer")
	endTimer := startMetricTimer(ctx, "client.call.serialization_duration")
	defer endTimer()
	defer span.End()
	input, ok := in.Parameters.(*PutMaintenanceStartTimeInput)
	if !ok {
		return out, metadata, fmt.Errorf("unexpected input type %T", in.Parameters)
	}
	_ = input

	req, ok := in.Request.(*smithyhttp.Request)
	if !ok {
		return out, metadata, fmt.Errorf("unexpected transport type %T", in.Request)
	}

	req.Method = http.MethodPost
	req.URL.Path = "/service/BackupOnPremises_v20210101/operation/PutMaintenanceStartTime"
	req.Header.Set("smithy-protocol", "rpc-v2-cbor")

	req.Header.Set("Content-Type", "application/cbor")
	req.Header.Set("Accept", "application/cbor")

	cv, err := serializeCBOR_PutMaintenanceStartTimeInput(input)
	if err != nil {
		return out, metadata, &smithy.SerializationError{Err: err}
	}

	payload := bytes.NewReader(smithycbor.Encode(cv))
	if req, err = req.SetStream(payload); err != nil {
		return out, metadata, &smithy.SerializationError{Err: err}
	}

	in.Request = req

	endTimer()
	span.End()

	return next.HandleSerialize(ctx, in)
}

type smithyRpcv2cbor_serializeOpStartVirtualMachinesMetadataSync struct {
}

func (*smithyRpcv2cbor_serializeOpStartVirtualMachinesMetadataSync) ID() string {
	return "OperationSerializer"
}

func (m *smithyRpcv2cbor_serializeOpStartVirtualMachinesMetadataSync) HandleSerialize(ctx context.Context, in middleware.SerializeInput, next middleware.SerializeHandler) (
	out middleware.SerializeOutput, metadata middleware.Metadata, err error,
) {
	_, span := tracing.StartSpan(ctx, "OperationSerializer")
	endTimer := startMetricTimer(ctx, "client.call.serialization_duration")
	defer endTimer()
	defer span.End()
	input, ok := in.Parameters.(*StartVirtualMachinesMetadataSyncInput)
	if !ok {
		return out, metadata, fmt.Errorf("unexpected input type %T", in.Parameters)
	}
	_ = input

	req, ok := in.Request.(*smithyhttp.Request)
	if !ok {
		return out, metadata, fmt.Errorf("unexpected transport type %T", in.Request)
	}

	req.Method = http.MethodPost
	req.URL.Path = "/service/BackupOnPremises_v20210101/operation/StartVirtualMachinesMetadataSync"
	req.Header.Set("smithy-protocol", "rpc-v2-cbor")

	req.Header.Set("Content-Type", "application/cbor")
	req.Header.Set("Accept", "application/cbor")

	cv, err := serializeCBOR_StartVirtualMachinesMetadataSyncInput(input)
	if err != nil {
		return out, metadata, &smithy.SerializationError{Err: err}
	}

	payload := bytes.NewReader(smithycbor.Encode(cv))
	if req, err = req.SetStream(payload); err != nil {
		return out, metadata, &smithy.SerializationError{Err: err}
	}

	in.Request = req

	endTimer()
	span.End()

	return next.HandleSerialize(ctx, in)
}

type smithyRpcv2cbor_serializeOpTagResource struct {
}

func (*smithyRpcv2cbor_serializeOpTagResource) ID() string {
	return "OperationSerializer"
}

func (m *smithyRpcv2cbor_serializeOpTagResource) HandleSerialize(ctx context.Context, in middleware.SerializeInput, next middleware.SerializeHandler) (
	out middleware.SerializeOutput, metadata middleware.Metadata, err error,
) {
	_, span := tracing.StartSpan(ctx, "OperationSerializer")
	endTimer := startMetricTimer(ctx, "client.call.serialization_duration")
	defer endTimer()
	defer span.End()
	input, ok := in.Parameters.(*TagResourceInput)
	if !ok {
		return out, metadata, fmt.Errorf("unexpected input type %T", in.Parameters)
	}
	_ = input

	req, ok := in.Request.(*smithyhttp.Request)
	if !ok {
		return out, metadata, fmt.Errorf("unexpected transport type %T", in.Request)
	}

	req.Method = http.MethodPost
	req.URL.Path = "/service/BackupOnPremises_v20210101/operation/TagResource"
	req.Header.Set("smithy-protocol", "rpc-v2-cbor")

	req.Header.Set("Content-Type", "application/cbor")
	req.Header.Set("Accept", "application/cbor")

	cv, err := serializeCBOR_TagResourceInput(input)
	if err != nil {
		return out, metadata, &smithy.SerializationError{Err: err}
	}

	payload := bytes.NewReader(smithycbor.Encode(cv))
	if req, err = req.SetStream(payload); err != nil {
		return out, metadata, &smithy.SerializationError{Err: err}
	}

	in.Request = req

	endTimer()
	span.End()

	return next.HandleSerialize(ctx, in)
}

type smithyRpcv2cbor_serializeOpTestHypervisorConfiguration struct {
}

func (*smithyRpcv2cbor_serializeOpTestHypervisorConfiguration) ID() string {
	return "OperationSerializer"
}

func (m *smithyRpcv2cbor_serializeOpTestHypervisorConfiguration) HandleSerialize(ctx context.Context, in middleware.SerializeInput, next middleware.SerializeHandler) (
	out middleware.SerializeOutput, metadata middleware.Metadata, err error,
) {
	_, span := tracing.StartSpan(ctx, "OperationSerializer")
	endTimer := startMetricTimer(ctx, "client.call.serialization_duration")
	defer endTimer()
	defer span.End()
	input, ok := in.Parameters.(*TestHypervisorConfigurationInput)
	if !ok {
		return out, metadata, fmt.Errorf("unexpected input type %T", in.Parameters)
	}
	_ = input

	req, ok := in.Request.(*smithyhttp.Request)
	if !ok {
		return out, metadata, fmt.Errorf("unexpected transport type %T", in.Request)
	}

	req.Method = http.MethodPost
	req.URL.Path = "/service/BackupOnPremises_v20210101/operation/TestHypervisorConfiguration"
	req.Header.Set("smithy-protocol", "rpc-v2-cbor")

	req.Header.Set("Content-Type", "application/cbor")
	req.Header.Set("Accept", "application/cbor")

	cv, err := serializeCBOR_TestHypervisorConfigurationInput(input)
	if err != nil {
		return out, metadata, &smithy.SerializationError{Err: err}
	}

	payload := bytes.NewReader(smithycbor.Encode(cv))
	if req, err = req.SetStream(payload); err != nil {
		return out, metadata, &smithy.SerializationError{Err: err}
	}

	in.Request = req

	endTimer()
	span.End()

	return next.HandleSerialize(ctx, in)
}

type smithyRpcv2cbor_serializeOpUntagResource struct {
}

func (*smithyRpcv2cbor_serializeOpUntagResource) ID() string {
	return "OperationSerializer"
}

func (m *smithyRpcv2cbor_serializeOpUntagResource) HandleSerialize(ctx context.Context, in middleware.SerializeInput, next middleware.SerializeHandler) (
	out middleware.SerializeOutput, metadata middleware.Metadata, err error,
) {
	_, span := tracing.StartSpan(ctx, "OperationSerializer")
	endTimer := startMetricTimer(ctx, "client.call.serialization_duration")
	defer endTimer()
	defer span.End()
	input, ok := in.Parameters.(*UntagResourceInput)
	if !ok {
		return out, metadata, fmt.Errorf("unexpected input type %T", in.Parameters)
	}
	_ = input

	req, ok := in.Request.(*smithyhttp.Request)
	if !ok {
		return out, metadata, fmt.Errorf("unexpected transport type %T", in.Request)
	}

	req.Method = http.MethodPost
	req.URL.Path = "/service/BackupOnPremises_v20210101/operation/UntagResource"
	req.Header.Set("smithy-protocol", "rpc-v2-cbor")

	req.Header.Set("Content-Type", "application/cbor")
	req.Header.Set("Accept", "application/cbor")

	cv, err := serializeCBOR_UntagResourceInput(input)
	if err != nil {
		return out, metadata, &smithy.SerializationError{Err: err}
	}

	payload := bytes.NewReader(smithycbor.Encode(cv))
	if req, err = req.SetStream(payload); err != nil {
		return out, metadata, &smithy.SerializationError{Err: err}
	}

	in.Request = req

	endTimer()
	span.End()

	return next.HandleSerialize(ctx, in)
}

type smithyRpcv2cbor_serializeOpUpdateGatewayInformation struct {
}

func (*smithyRpcv2cbor_serializeOpUpdateGatewayInformation) ID() string {
	return "OperationSerializer"
}

func (m *smithyRpcv2cbor_serializeOpUpdateGatewayInformation) HandleSerialize(ctx context.Context, in middleware.SerializeInput, next middleware.SerializeHandler) (
	out middleware.SerializeOutput, metadata middleware.Metadata, err error,
) {
	_, span := tracing.StartSpan(ctx, "OperationSerializer")
	endTimer := startMetricTimer(ctx, "client.call.serialization_duration")
	defer endTimer()
	defer span.End()
	input, ok := in.Parameters.(*UpdateGatewayInformationInput)
	if !ok {
		return out, metadata, fmt.Errorf("unexpected input type %T", in.Parameters)
	}
	_ = input

	req, ok := in.Request.(*smithyhttp.Request)
	if !ok {
		return out, metadata, fmt.Errorf("unexpected transport type %T", in.Request)
	}

	req.Method = http.MethodPost
	req.URL.Path = "/service/BackupOnPremises_v20210101/operation/UpdateGatewayInformation"
	req.Header.Set("smithy-protocol", "rpc-v2-cbor")

	req.Header.Set("Content-Type", "application/cbor")
	req.Header.Set("Accept", "application/cbor")

	cv, err := serializeCBOR_UpdateGatewayInformationInput(input)
	if err != nil {
		return out, metadata, &smithy.SerializationError{Err: err}
	}

	payload := bytes.NewReader(smithycbor.Encode(cv))
	if req, err = req.SetStream(payload); err != nil {
		return out, metadata, &smithy.SerializationError{Err: err}
	}

	in.Request = req

	endTimer()
	span.End()

	return next.HandleSerialize(ctx, in)
}

type smithyRpcv2cbor_serializeOpUpdateGatewaySoftwareNow struct {
}

func (*smithyRpcv2cbor_serializeOpUpdateGatewaySoftwareNow) ID() string {
	return "OperationSerializer"
}

func (m *smithyRpcv2cbor_serializeOpUpdateGatewaySoftwareNow) HandleSerialize(ctx context.Context, in middleware.SerializeInput, next middleware.SerializeHandler) (
	out middleware.SerializeOutput, metadata middleware.Metadata, err error,
) {
	_, span := tracing.StartSpan(ctx, "OperationSerializer")
	endTimer := startMetricTimer(ctx, "client.call.serialization_duration")
	defer endTimer()
	defer span.End()
	input, ok := in.Parameters.(*UpdateGatewaySoftwareNowInput)
	if !ok {
		return out, metadata, fmt.Errorf("unexpected input type %T", in.Parameters)
	}
	_ = input

	req, ok := in.Request.(*smithyhttp.Request)
	if !ok {
		return out, metadata, fmt.Errorf("unexpected transport type %T", in.Request)
	}

	req.Method = http.MethodPost
	req.URL.Path = "/service/BackupOnPremises_v20210101/operation/UpdateGatewaySoftwareNow"
	req.Header.Set("smithy-protocol", "rpc-v2-cbor")

	req.Header.Set("Content-Type", "application/cbor")
	req.Header.Set("Accept", "application/cbor")

	cv, err := serializeCBOR_UpdateGatewaySoftwareNowInput(input)
	if err != nil {
		return out, metadata, &smithy.SerializationError{Err: err}
	}

	payload := bytes.NewReader(smithycbor.Encode(cv))
	if req, err = req.SetStream(payload); err != nil {
		return out, metadata, &smithy.SerializationError{Err: err}
	}

	in.Request = req

	endTimer()
	span.End()

	return next.HandleSerialize(ctx, in)
}

type smithyRpcv2cbor_serializeOpUpdateHypervisor struct {
}

func (*smithyRpcv2cbor_serializeOpUpdateHypervisor) ID() string {
	return "OperationSerializer"
}

func (m *smithyRpcv2cbor_serializeOpUpdateHypervisor) HandleSerialize(ctx context.Context, in middleware.SerializeInput, next middleware.SerializeHandler) (
	out middleware.SerializeOutput, metadata middleware.Metadata, err error,
) {
	_, span := tracing.StartSpan(ctx, "OperationSerializer")
	endTimer := startMetricTimer(ctx, "client.call.serialization_duration")
	defer endTimer()
	defer span.End()
	input, ok := in.Parameters.(*UpdateHypervisorInput)
	if !ok {
		return out, metadata, fmt.Errorf("unexpected input type %T", in.Parameters)
	}
	_ = input

	req, ok := in.Request.(*smithyhttp.Request)
	if !ok {
		return out, metadata, fmt.Errorf("unexpected transport type %T", in.Request)
	}

	req.Method = http.MethodPost
	req.URL.Path = "/service/BackupOnPremises_v20210101/operation/UpdateHypervisor"
	req.Header.Set("smithy-protocol", "rpc-v2-cbor")

	req.Header.Set("Content-Type", "application/cbor")
	req.Header.Set("Accept", "application/cbor")

	cv, err := serializeCBOR_UpdateHypervisorInput(input)
	if err != nil {
		return out, metadata, &smithy.SerializationError{Err: err}
	}

	payload := bytes.NewReader(smithycbor.Encode(cv))
	if req, err = req.SetStream(payload); err != nil {
		return out, metadata, &smithy.SerializationError{Err: err}
	}

	in.Request = req

	endTimer()
	span.End()

	return next.HandleSerialize(ctx, in)
}
func serializeCBOR_BandwidthRateLimitInterval(v *types.BandwidthRateLimitInterval) (smithycbor.Value, error) {
	vm := smithycbor.Map{}
	if v.AverageUploadRateLimitInBitsPerSec != nil {
		ser, err := serializeCBOR_Int64(*v.AverageUploadRateLimitInBitsPerSec)
		if err != nil {
			return nil, err
		}
		vm["AverageUploadRateLimitInBitsPerSec"] = ser
	}
	if v.StartHourOfDay != nil {
		ser, err := serializeCBOR_Int32(*v.StartHourOfDay)
		if err != nil {
			return nil, err
		}
		vm["StartHourOfDay"] = ser
	}
	if v.EndHourOfDay != nil {
		ser, err := serializeCBOR_Int32(*v.EndHourOfDay)
		if err != nil {
			return nil, err
		}
		vm["EndHourOfDay"] = ser
	}
	if v.StartMinuteOfHour != nil {
		ser, err := serializeCBOR_Int32(*v.StartMinuteOfHour)
		if err != nil {
			return nil, err
		}
		vm["StartMinuteOfHour"] = ser
	}
	if v.EndMinuteOfHour != nil {
		ser, err := serializeCBOR_Int32(*v.EndMinuteOfHour)
		if err != nil {
			return nil, err
		}
		vm["EndMinuteOfHour"] = ser
	}
	if v.DaysOfWeek != nil {
		ser, err := serializeCBOR_DaysOfWeek(v.DaysOfWeek)
		if err != nil {
			return nil, err
		}
		vm["DaysOfWeek"] = ser
	}
	return vm, nil
}

func serializeCBOR_BandwidthRateLimitIntervals(v []types.BandwidthRateLimitInterval) (smithycbor.Value, error) {
	vl := smithycbor.List{}
	for i := range v {

		ser, err := serializeCBOR_BandwidthRateLimitInterval(&v[i])
		if err != nil {
			return nil, err
		}
		vl = append(vl, ser)
	}
	return vl, nil
}

func serializeCBOR_DaysOfWeek(v []int32) (smithycbor.Value, error) {
	vl := smithycbor.List{}
	for i := range v {

		ser, err := serializeCBOR_Int32(v[i])
		if err != nil {
			return nil, err
		}
		vl = append(vl, ser)
	}
	return vl, nil
}

func serializeCBOR_GatewayType(v types.GatewayType) (smithycbor.Value, error) {
	return smithycbor.String(string(v)), nil
}

func serializeCBOR_Tag(v *types.Tag) (smithycbor.Value, error) {
	vm := smithycbor.Map{}
	if v.Key != nil {
		ser, err := serializeCBOR_String(*v.Key)
		if err != nil {
			return nil, err
		}
		vm["Key"] = ser
	}
	if v.Value != nil {
		ser, err := serializeCBOR_String(*v.Value)
		if err != nil {
			return nil, err
		}
		vm["Value"] = ser
	}
	return vm, nil
}

func serializeCBOR_TagKeys(v []string) (smithycbor.Value, error) {
	vl := smithycbor.List{}
	for i := range v {

		ser, err := serializeCBOR_String(v[i])
		if err != nil {
			return nil, err
		}
		vl = append(vl, ser)
	}
	return vl, nil
}

func serializeCBOR_Tags(v []types.Tag) (smithycbor.Value, error) {
	vl := smithycbor.List{}
	for i := range v {

		ser, err := serializeCBOR_Tag(&v[i])
		if err != nil {
			return nil, err
		}
		vl = append(vl, ser)
	}
	return vl, nil
}

func serializeCBOR_VmwareToAwsTagMapping(v *types.VmwareToAwsTagMapping) (smithycbor.Value, error) {
	vm := smithycbor.Map{}
	if v.VmwareCategory != nil {
		ser, err := serializeCBOR_String(*v.VmwareCategory)
		if err != nil {
			return nil, err
		}
		vm["VmwareCategory"] = ser
	}
	if v.VmwareTagName != nil {
		ser, err := serializeCBOR_String(*v.VmwareTagName)
		if err != nil {
			return nil, err
		}
		vm["VmwareTagName"] = ser
	}
	if v.AwsTagKey != nil {
		ser, err := serializeCBOR_String(*v.AwsTagKey)
		if err != nil {
			return nil, err
		}
		vm["AwsTagKey"] = ser
	}
	if v.AwsTagValue != nil {
		ser, err := serializeCBOR_String(*v.AwsTagValue)
		if err != nil {
			return nil, err
		}
		vm["AwsTagValue"] = ser
	}
	return vm, nil
}

func serializeCBOR_VmwareToAwsTagMappings(v []types.VmwareToAwsTagMapping) (smithycbor.Value, error) {
	vl := smithycbor.List{}
	for i := range v {

		ser, err := serializeCBOR_VmwareToAwsTagMapping(&v[i])
		if err != nil {
			return nil, err
		}
		vl = append(vl, ser)
	}
	return vl, nil
}

func serializeCBOR_Int32(v int32) (smithycbor.Value, error) {
	if v < 0 {
		return smithycbor.NegInt(uint64(-v)), nil
	}
	return smithycbor.Uint(uint64(v)), nil
}

func serializeCBOR_Int64(v int64) (smithycbor.Value, error) {
	if v < 0 {
		return smithycbor.NegInt(uint64(-v)), nil
	}
	return smithycbor.Uint(uint64(v)), nil
}

func serializeCBOR_String(v string) (smithycbor.Value, error) {
	return smithycbor.String(v), nil
}

func serializeCBOR_AssociateGatewayToServerInput(v *AssociateGatewayToServerInput) (smithycbor.Value, error) {
	vm := smithycbor.Map{}
	if v.GatewayArn != nil {
		ser, err := serializeCBOR_String(*v.GatewayArn)
		if err != nil {
			return nil, err
		}
		vm["GatewayArn"] = ser
	}
	if v.ServerArn != nil {
		ser, err := serializeCBOR_String(*v.ServerArn)
		if err != nil {
			return nil, err
		}
		vm["ServerArn"] = ser
	}
	return vm, nil
}

func serializeCBOR_CreateGatewayInput(v *CreateGatewayInput) (smithycbor.Value, error) {
	vm := smithycbor.Map{}
	if v.ActivationKey != nil {
		ser, err := serializeCBOR_String(*v.ActivationKey)
		if err != nil {
			return nil, err
		}
		vm["ActivationKey"] = ser
	}
	if v.GatewayDisplayName != nil {
		ser, err := serializeCBOR_String(*v.GatewayDisplayName)
		if err != nil {
			return nil, err
		}
		vm["GatewayDisplayName"] = ser
	}
	if len(v.GatewayType) > 0 {
		ser, err := serializeCBOR_GatewayType(v.GatewayType)
		if err != nil {
			return nil, err
		}
		vm["GatewayType"] = ser
	}
	if v.Tags != nil {
		ser, err := serializeCBOR_Tags(v.Tags)
		if err != nil {
			return nil, err
		}
		vm["Tags"] = ser
	}
	return vm, nil
}

func serializeCBOR_DeleteGatewayInput(v *DeleteGatewayInput) (smithycbor.Value, error) {
	vm := smithycbor.Map{}
	if v.GatewayArn != nil {
		ser, err := serializeCBOR_String(*v.GatewayArn)
		if err != nil {
			return nil, err
		}
		vm["GatewayArn"] = ser
	}
	return vm, nil
}

func serializeCBOR_DeleteHypervisorInput(v *DeleteHypervisorInput) (smithycbor.Value, error) {
	vm := smithycbor.Map{}
	if v.HypervisorArn != nil {
		ser, err := serializeCBOR_String(*v.HypervisorArn)
		if err != nil {
			return nil, err
		}
		vm["HypervisorArn"] = ser
	}
	return vm, nil
}

func serializeCBOR_DisassociateGatewayFromServerInput(v *DisassociateGatewayFromServerInput) (smithycbor.Value, error) {
	vm := smithycbor.Map{}
	if v.GatewayArn != nil {
		ser, err := serializeCBOR_String(*v.GatewayArn)
		if err != nil {
			return nil, err
		}
		vm["GatewayArn"] = ser
	}
	return vm, nil
}

func serializeCBOR_GetBandwidthRateLimitScheduleInput(v *GetBandwidthRateLimitScheduleInput) (smithycbor.Value, error) {
	vm := smithycbor.Map{}
	if v.GatewayArn != nil {
		ser, err := serializeCBOR_String(*v.GatewayArn)
		if err != nil {
			return nil, err
		}
		vm["GatewayArn"] = ser
	}
	return vm, nil
}

func serializeCBOR_GetGatewayInput(v *GetGatewayInput) (smithycbor.Value, error) {
	vm := smithycbor.Map{}
	if v.GatewayArn != nil {
		ser, err := serializeCBOR_String(*v.GatewayArn)
		if err != nil {
			return nil, err
		}
		vm["GatewayArn"] = ser
	}
	return vm, nil
}

func serializeCBOR_GetHypervisorInput(v *GetHypervisorInput) (smithycbor.Value, error) {
	vm := smithycbor.Map{}
	if v.HypervisorArn != nil {
		ser, err := serializeCBOR_String(*v.HypervisorArn)
		if err != nil {
			return nil, err
		}
		vm["HypervisorArn"] = ser
	}
	return vm, nil
}

func serializeCBOR_GetHypervisorPropertyMappingsInput(v *GetHypervisorPropertyMappingsInput) (smithycbor.Value, error) {
	vm := smithycbor.Map{}
	if v.HypervisorArn != nil {
		ser, err := serializeCBOR_String(*v.HypervisorArn)
		if err != nil {
			return nil, err
		}
		vm["HypervisorArn"] = ser
	}
	return vm, nil
}

func serializeCBOR_GetVirtualMachineInput(v *GetVirtualMachineInput) (smithycbor.Value, error) {
	vm := smithycbor.Map{}
	if v.ResourceArn != nil {
		ser, err := serializeCBOR_String(*v.ResourceArn)
		if err != nil {
			return nil, err
		}
		vm["ResourceArn"] = ser
	}
	return vm, nil
}

func serializeCBOR_ImportHypervisorConfigurationInput(v *ImportHypervisorConfigurationInput) (smithycbor.Value, error) {
	vm := smithycbor.Map{}
	if v.Name != nil {
		ser, err := serializeCBOR_String(*v.Name)
		if err != nil {
			return nil, err
		}
		vm["Name"] = ser
	}
	if v.Host != nil {
		ser, err := serializeCBOR_String(*v.Host)
		if err != nil {
			return nil, err
		}
		vm["Host"] = ser
	}
	if v.Username != nil {
		ser, err := serializeCBOR_String(*v.Username)
		if err != nil {
			return nil, err
		}
		vm["Username"] = ser
	}
	if v.Password != nil {
		ser, err := serializeCBOR_String(*v.Password)
		if err != nil {
			return nil, err
		}
		vm["Password"] = ser
	}
	if v.KmsKeyArn != nil {
		ser, err := serializeCBOR_String(*v.KmsKeyArn)
		if err != nil {
			return nil, err
		}
		vm["KmsKeyArn"] = ser
	}
	if v.Tags != nil {
		ser, err := serializeCBOR_Tags(v.Tags)
		if err != nil {
			return nil, err
		}
		vm["Tags"] = ser
	}
	return vm, nil
}

func serializeCBOR_ListGatewaysInput(v *ListGatewaysInput) (smithycbor.Value, error) {
	vm := smithycbor.Map{}
	if v.MaxResults != nil {
		ser, err := serializeCBOR_Int32(*v.MaxResults)
		if err != nil {
			return nil, err
		}
		vm["MaxResults"] = ser
	}
	if v.NextToken != nil {
		ser, err := serializeCBOR_String(*v.NextToken)
		if err != nil {
			return nil, err
		}
		vm["NextToken"] = ser
	}
	return vm, nil
}

func serializeCBOR_ListHypervisorsInput(v *ListHypervisorsInput) (smithycbor.Value, error) {
	vm := smithycbor.Map{}
	if v.MaxResults != nil {
		ser, err := serializeCBOR_Int32(*v.MaxResults)
		if err != nil {
			return nil, err
		}
		vm["MaxResults"] = ser
	}
	if v.NextToken != nil {
		ser, err := serializeCBOR_String(*v.NextToken)
		if err != nil {
			return nil, err
		}
		vm["NextToken"] = ser
	}
	return vm, nil
}

func serializeCBOR_ListTagsForResourceInput(v *ListTagsForResourceInput) (smithycbor.Value, error) {
	vm := smithycbor.Map{}
	if v.ResourceArn != nil {
		ser, err := serializeCBOR_String(*v.ResourceArn)
		if err != nil {
			return nil, err
		}
		vm["ResourceArn"] = ser
	}
	return vm, nil
}

func serializeCBOR_ListVirtualMachinesInput(v *ListVirtualMachinesInput) (smithycbor.Value, error) {
	vm := smithycbor.Map{}
	if v.HypervisorArn != nil {
		ser, err := serializeCBOR_String(*v.HypervisorArn)
		if err != nil {
			return nil, err
		}
		vm["HypervisorArn"] = ser
	}
	if v.MaxResults != nil {
		ser, err := serializeCBOR_Int32(*v.MaxResults)
		if err != nil {
			return nil, err
		}
		vm["MaxResults"] = ser
	}
	if v.NextToken != nil {
		ser, err := serializeCBOR_String(*v.NextToken)
		if err != nil {
			return nil, err
		}
		vm["NextToken"] = ser
	}
	return vm, nil
}

func serializeCBOR_PutBandwidthRateLimitScheduleInput(v *PutBandwidthRateLimitScheduleInput) (smithycbor.Value, error) {
	vm := smithycbor.Map{}
	if v.GatewayArn != nil {
		ser, err := serializeCBOR_String(*v.GatewayArn)
		if err != nil {
			return nil, err
		}
		vm["GatewayArn"] = ser
	}
	if v.BandwidthRateLimitIntervals != nil {
		ser, err := serializeCBOR_BandwidthRateLimitIntervals(v.BandwidthRateLimitIntervals)
		if err != nil {
			return nil, err
		}
		vm["BandwidthRateLimitIntervals"] = ser
	}
	return vm, nil
}

func serializeCBOR_PutHypervisorPropertyMappingsInput(v *PutHypervisorPropertyMappingsInput) (smithycbor.Value, error) {
	vm := smithycbor.Map{}
	if v.HypervisorArn != nil {
		ser, err := serializeCBOR_String(*v.HypervisorArn)
		if err != nil {
			return nil, err
		}
		vm["HypervisorArn"] = ser
	}
	if v.VmwareToAwsTagMappings != nil {
		ser, err := serializeCBOR_VmwareToAwsTagMappings(v.VmwareToAwsTagMappings)
		if err != nil {
			return nil, err
		}
		vm["VmwareToAwsTagMappings"] = ser
	}
	if v.IamRoleArn != nil {
		ser, err := serializeCBOR_String(*v.IamRoleArn)
		if err != nil {
			return nil, err
		}
		vm["IamRoleArn"] = ser
	}
	return vm, nil
}

func serializeCBOR_PutMaintenanceStartTimeInput(v *PutMaintenanceStartTimeInput) (smithycbor.Value, error) {
	vm := smithycbor.Map{}
	if v.GatewayArn != nil {
		ser, err := serializeCBOR_String(*v.GatewayArn)
		if err != nil {
			return nil, err
		}
		vm["GatewayArn"] = ser
	}
	if v.HourOfDay != nil {
		ser, err := serializeCBOR_Int32(*v.HourOfDay)
		if err != nil {
			return nil, err
		}
		vm["HourOfDay"] = ser
	}
	if v.MinuteOfHour != nil {
		ser, err := serializeCBOR_Int32(*v.MinuteOfHour)
		if err != nil {
			return nil, err
		}
		vm["MinuteOfHour"] = ser
	}
	if v.DayOfWeek != nil {
		ser, err := serializeCBOR_Int32(*v.DayOfWeek)
		if err != nil {
			return nil, err
		}
		vm["DayOfWeek"] = ser
	}
	if v.DayOfMonth != nil {
		ser, err := serializeCBOR_Int32(*v.DayOfMonth)
		if err != nil {
			return nil, err
		}
		vm["DayOfMonth"] = ser
	}
	return vm, nil
}

func serializeCBOR_StartVirtualMachinesMetadataSyncInput(v *StartVirtualMachinesMetadataSyncInput) (smithycbor.Value, error) {
	vm := smithycbor.Map{}
	if v.HypervisorArn != nil {
		ser, err := serializeCBOR_String(*v.HypervisorArn)
		if err != nil {
			return nil, err
		}
		vm["HypervisorArn"] = ser
	}
	return vm, nil
}

func serializeCBOR_TagResourceInput(v *TagResourceInput) (smithycbor.Value, error) {
	vm := smithycbor.Map{}
	if v.ResourceARN != nil {
		ser, err := serializeCBOR_String(*v.ResourceARN)
		if err != nil {
			return nil, err
		}
		vm["ResourceARN"] = ser
	}
	if v.Tags != nil {
		ser, err := serializeCBOR_Tags(v.Tags)
		if err != nil {
			return nil, err
		}
		vm["Tags"] = ser
	}
	return vm, nil
}

func serializeCBOR_TestHypervisorConfigurationInput(v *TestHypervisorConfigurationInput) (smithycbor.Value, error) {
	vm := smithycbor.Map{}
	if v.GatewayArn != nil {
		ser, err := serializeCBOR_String(*v.GatewayArn)
		if err != nil {
			return nil, err
		}
		vm["GatewayArn"] = ser
	}
	if v.Host != nil {
		ser, err := serializeCBOR_String(*v.Host)
		if err != nil {
			return nil, err
		}
		vm["Host"] = ser
	}
	if v.Username != nil {
		ser, err := serializeCBOR_String(*v.Username)
		if err != nil {
			return nil, err
		}
		vm["Username"] = ser
	}
	if v.Password != nil {
		ser, err := serializeCBOR_String(*v.Password)
		if err != nil {
			return nil, err
		}
		vm["Password"] = ser
	}
	return vm, nil
}

func serializeCBOR_UntagResourceInput(v *UntagResourceInput) (smithycbor.Value, error) {
	vm := smithycbor.Map{}
	if v.ResourceARN != nil {
		ser, err := serializeCBOR_String(*v.ResourceARN)
		if err != nil {
			return nil, err
		}
		vm["ResourceARN"] = ser
	}
	if v.TagKeys != nil {
		ser, err := serializeCBOR_TagKeys(v.TagKeys)
		if err != nil {
			return nil, err
		}
		vm["TagKeys"] = ser
	}
	return vm, nil
}

func serializeCBOR_UpdateGatewayInformationInput(v *UpdateGatewayInformationInput) (smithycbor.Value, error) {
	vm := smithycbor.Map{}
	if v.GatewayArn != nil {
		ser, err := serializeCBOR_String(*v.GatewayArn)
		if err != nil {
			return nil, err
		}
		vm["GatewayArn"] = ser
	}
	if v.GatewayDisplayName != nil {
		ser, err := serializeCBOR_String(*v.GatewayDisplayName)
		if err != nil {
			return nil, err
		}
		vm["GatewayDisplayName"] = ser
	}
	return vm, nil
}

func serializeCBOR_UpdateGatewaySoftwareNowInput(v *UpdateGatewaySoftwareNowInput) (smithycbor.Value, error) {
	vm := smithycbor.Map{}
	if v.GatewayArn != nil {
		ser, err := serializeCBOR_String(*v.GatewayArn)
		if err != nil {
			return nil, err
		}
		vm["GatewayArn"] = ser
	}
	return vm, nil
}

func serializeCBOR_UpdateHypervisorInput(v *UpdateHypervisorInput) (smithycbor.Value, error) {
	vm := smithycbor.Map{}
	if v.HypervisorArn != nil {
		ser, err := serializeCBOR_String(*v.HypervisorArn)
		if err != nil {
			return nil, err
		}
		vm["HypervisorArn"] = ser
	}
	if v.Host != nil {
		ser, err := serializeCBOR_String(*v.Host)
		if err != nil {
			return nil, err
		}
		vm["Host"] = ser
	}
	if v.Username != nil {
		ser, err := serializeCBOR_String(*v.Username)
		if err != nil {
			return nil, err
		}
		vm["Username"] = ser
	}
	if v.Password != nil {
		ser, err := serializeCBOR_String(*v.Password)
		if err != nil {
			return nil, err
		}
		vm["Password"] = ser
	}
	if v.Name != nil {
		ser, err := serializeCBOR_String(*v.Name)
		if err != nil {
			return nil, err
		}
		vm["Name"] = ser
	}
	if v.LogGroupArn != nil {
		ser, err := serializeCBOR_String(*v.LogGroupArn)
		if err != nil {
			return nil, err
		}
		vm["LogGroupArn"] = ser
	}
	return vm, nil
}
