// Code generated by smithy-go-codegen DO NOT EDIT.

package bcmrecommendedactions

import (
	"bytes"
	"context"
	"fmt"
	"github.com/aws/aws-sdk-go-v2/service/bcmrecommendedactions/types"
	smithy "github.com/aws/smithy-go"
	smithycbor "github.com/aws/smithy-go/encoding/cbor"
	"github.com/aws/smithy-go/middleware"
	"github.com/aws/smithy-go/tracing"
	smithyhttp "github.com/aws/smithy-go/transport/http"
	"net/http"
)

type smithyRpcv2cbor_serializeOpListRecommendedActions struct {
}

func (*smithyRpcv2cbor_serializeOpListRecommendedActions) ID() string {
	return "OperationSerializer"
}

func (m *smithyRpcv2cbor_serializeOpListRecommendedActions) HandleSerialize(ctx context.Context, in middleware.SerializeInput, next middleware.SerializeHandler) (
	out middleware.SerializeOutput, metadata middleware.Metadata, err error,
) {
	_, span := tracing.StartSpan(ctx, "OperationSerializer")
	endTimer := startMetricTimer(ctx, "client.call.serialization_duration")
	defer endTimer()
	defer span.End()
	input, ok := in.Parameters.(*ListRecommendedActionsInput)
	if !ok {
		return out, metadata, fmt.Errorf("unexpected input type %T", in.Parameters)
	}
	_ = input

	req, ok := in.Request.(*smithyhttp.Request)
	if !ok {
		return out, metadata, fmt.Errorf("unexpected transport type %T", in.Request)
	}

	req.Method = http.MethodPost
	req.URL.Path = "/service/AWSBillingAndCostManagementRecommendedActions/operation/ListRecommendedActions"
	req.Header.Set("smithy-protocol", "rpc-v2-cbor")

	req.Header.Set("Content-Type", "application/cbor")
	req.Header.Set("Accept", "application/cbor")

	cv, err := serializeCBOR_ListRecommendedActionsInput(input)
	if err != nil {
		return out, metadata, &smithy.SerializationError{Err: err}
	}

	payload := bytes.NewReader(smithycbor.Encode(cv))
	if req, err = req.SetStream(payload); err != nil {
		return out, metadata, &smithy.SerializationError{Err: err}
	}

	in.Request = req

	endTimer()
	span.End()

	return next.HandleSerialize(ctx, in)
}
func serializeCBOR_ActionFilter(v *types.ActionFilter) (smithycbor.Value, error) {
	vm := smithycbor.Map{}
	if len(v.Key) > 0 {
		ser, err := serializeCBOR_FilterName(v.Key)
		if err != nil {
			return nil, err
		}
		vm["key"] = ser
	}
	if len(v.MatchOption) > 0 {
		ser, err := serializeCBOR_MatchOption(v.MatchOption)
		if err != nil {
			return nil, err
		}
		vm["matchOption"] = ser
	}
	if v.Values != nil {
		ser, err := serializeCBOR_FilterValues(v.Values)
		if err != nil {
			return nil, err
		}
		vm["values"] = ser
	}
	return vm, nil
}

func serializeCBOR_ActionFilterList(v []types.ActionFilter) (smithycbor.Value, error) {
	vl := smithycbor.List{}
	for i := range v {

		ser, err := serializeCBOR_ActionFilter(&v[i])
		if err != nil {
			return nil, err
		}
		vl = append(vl, ser)
	}
	return vl, nil
}

func serializeCBOR_FilterName(v types.FilterName) (smithycbor.Value, error) {
	return smithycbor.String(string(v)), nil
}

func serializeCBOR_FilterValues(v []string) (smithycbor.Value, error) {
	vl := smithycbor.List{}
	for i := range v {

		ser, err := serializeCBOR_String(v[i])
		if err != nil {
			return nil, err
		}
		vl = append(vl, ser)
	}
	return vl, nil
}

func serializeCBOR_MatchOption(v types.MatchOption) (smithycbor.Value, error) {
	return smithycbor.String(string(v)), nil
}

func serializeCBOR_RequestFilter(v *types.RequestFilter) (smithycbor.Value, error) {
	vm := smithycbor.Map{}
	if v.Actions != nil {
		ser, err := serializeCBOR_ActionFilterList(v.Actions)
		if err != nil {
			return nil, err
		}
		vm["actions"] = ser
	}
	return vm, nil
}

func serializeCBOR_Int32(v int32) (smithycbor.Value, error) {
	if v < 0 {
		return smithycbor.NegInt(uint64(-v)), nil
	}
	return smithycbor.Uint(uint64(v)), nil
}

func serializeCBOR_String(v string) (smithycbor.Value, error) {
	return smithycbor.String(v), nil
}

func serializeCBOR_ListRecommendedActionsInput(v *ListRecommendedActionsInput) (smithycbor.Value, error) {
	vm := smithycbor.Map{}
	if v.Filter != nil {
		ser, err := serializeCBOR_RequestFilter(v.Filter)
		if err != nil {
			return nil, err
		}
		vm["filter"] = ser
	}
	if v.MaxResults != nil {
		ser, err := serializeCBOR_Int32(*v.MaxResults)
		if err != nil {
			return nil, err
		}
		vm["maxResults"] = ser
	}
	if v.NextToken != nil {
		ser, err := serializeCBOR_String(*v.NextToken)
		if err != nil {
			return nil, err
		}
		vm["nextToken"] = ser
	}
	return vm, nil
}
