// Code generated by smithy-go-codegen DO NOT EDIT.

package kendraranking

import (
	"bytes"
	"context"
	"fmt"
	"github.com/aws/aws-sdk-go-v2/service/kendraranking/types"
	smithy "github.com/aws/smithy-go"
	smithycbor "github.com/aws/smithy-go/encoding/cbor"
	"github.com/aws/smithy-go/middleware"
	"github.com/aws/smithy-go/tracing"
	smithyhttp "github.com/aws/smithy-go/transport/http"
	"net/http"
)

type smithyRpcv2cbor_serializeOpCreateRescoreExecutionPlan struct {
}

func (*smithyRpcv2cbor_serializeOpCreateRescoreExecutionPlan) ID() string {
	return "OperationSerializer"
}

func (m *smithyRpcv2cbor_serializeOpCreateRescoreExecutionPlan) HandleSerialize(ctx context.Context, in middleware.SerializeInput, next middleware.SerializeHandler) (
	out middleware.SerializeOutput, metadata middleware.Metadata, err error,
) {
	_, span := tracing.StartSpan(ctx, "OperationSerializer")
	endTimer := startMetricTimer(ctx, "client.call.serialization_duration")
	defer endTimer()
	defer span.End()
	input, ok := in.Parameters.(*CreateRescoreExecutionPlanInput)
	if !ok {
		return out, metadata, fmt.Errorf("unexpected input type %T", in.Parameters)
	}
	_ = input

	req, ok := in.Request.(*smithyhttp.Request)
	if !ok {
		return out, metadata, fmt.Errorf("unexpected transport type %T", in.Request)
	}

	req.Method = http.MethodPost
	req.URL.Path = "/service/AWSKendraRerankingFrontendService/operation/CreateRescoreExecutionPlan"
	req.Header.Set("smithy-protocol", "rpc-v2-cbor")

	req.Header.Set("Content-Type", "application/cbor")
	req.Header.Set("Accept", "application/cbor")

	cv, err := serializeCBOR_CreateRescoreExecutionPlanInput(input)
	if err != nil {
		return out, metadata, &smithy.SerializationError{Err: err}
	}

	payload := bytes.NewReader(smithycbor.Encode(cv))
	if req, err = req.SetStream(payload); err != nil {
		return out, metadata, &smithy.SerializationError{Err: err}
	}

	in.Request = req

	endTimer()
	span.End()

	return next.HandleSerialize(ctx, in)
}

type smithyRpcv2cbor_serializeOpDeleteRescoreExecutionPlan struct {
}

func (*smithyRpcv2cbor_serializeOpDeleteRescoreExecutionPlan) ID() string {
	return "OperationSerializer"
}

func (m *smithyRpcv2cbor_serializeOpDeleteRescoreExecutionPlan) HandleSerialize(ctx context.Context, in middleware.SerializeInput, next middleware.SerializeHandler) (
	out middleware.SerializeOutput, metadata middleware.Metadata, err error,
) {
	_, span := tracing.StartSpan(ctx, "OperationSerializer")
	endTimer := startMetricTimer(ctx, "client.call.serialization_duration")
	defer endTimer()
	defer span.End()
	input, ok := in.Parameters.(*DeleteRescoreExecutionPlanInput)
	if !ok {
		return out, metadata, fmt.Errorf("unexpected input type %T", in.Parameters)
	}
	_ = input

	req, ok := in.Request.(*smithyhttp.Request)
	if !ok {
		return out, metadata, fmt.Errorf("unexpected transport type %T", in.Request)
	}

	req.Method = http.MethodPost
	req.URL.Path = "/service/AWSKendraRerankingFrontendService/operation/DeleteRescoreExecutionPlan"
	req.Header.Set("smithy-protocol", "rpc-v2-cbor")

	req.Header.Set("Content-Type", "application/cbor")
	req.Header.Set("Accept", "application/cbor")

	cv, err := serializeCBOR_DeleteRescoreExecutionPlanInput(input)
	if err != nil {
		return out, metadata, &smithy.SerializationError{Err: err}
	}

	payload := bytes.NewReader(smithycbor.Encode(cv))
	if req, err = req.SetStream(payload); err != nil {
		return out, metadata, &smithy.SerializationError{Err: err}
	}

	in.Request = req

	endTimer()
	span.End()

	return next.HandleSerialize(ctx, in)
}

type smithyRpcv2cbor_serializeOpDescribeRescoreExecutionPlan struct {
}

func (*smithyRpcv2cbor_serializeOpDescribeRescoreExecutionPlan) ID() string {
	return "OperationSerializer"
}

func (m *smithyRpcv2cbor_serializeOpDescribeRescoreExecutionPlan) HandleSerialize(ctx context.Context, in middleware.SerializeInput, next middleware.SerializeHandler) (
	out middleware.SerializeOutput, metadata middleware.Metadata, err error,
) {
	_, span := tracing.StartSpan(ctx, "OperationSerializer")
	endTimer := startMetricTimer(ctx, "client.call.serialization_duration")
	defer endTimer()
	defer span.End()
	input, ok := in.Parameters.(*DescribeRescoreExecutionPlanInput)
	if !ok {
		return out, metadata, fmt.Errorf("unexpected input type %T", in.Parameters)
	}
	_ = input

	req, ok := in.Request.(*smithyhttp.Request)
	if !ok {
		return out, metadata, fmt.Errorf("unexpected transport type %T", in.Request)
	}

	req.Method = http.MethodPost
	req.URL.Path = "/service/AWSKendraRerankingFrontendService/operation/DescribeRescoreExecutionPlan"
	req.Header.Set("smithy-protocol", "rpc-v2-cbor")

	req.Header.Set("Content-Type", "application/cbor")
	req.Header.Set("Accept", "application/cbor")

	cv, err := serializeCBOR_DescribeRescoreExecutionPlanInput(input)
	if err != nil {
		return out, metadata, &smithy.SerializationError{Err: err}
	}

	payload := bytes.NewReader(smithycbor.Encode(cv))
	if req, err = req.SetStream(payload); err != nil {
		return out, metadata, &smithy.SerializationError{Err: err}
	}

	in.Request = req

	endTimer()
	span.End()

	return next.HandleSerialize(ctx, in)
}

type smithyRpcv2cbor_serializeOpListRescoreExecutionPlans struct {
}

func (*smithyRpcv2cbor_serializeOpListRescoreExecutionPlans) ID() string {
	return "OperationSerializer"
}

func (m *smithyRpcv2cbor_serializeOpListRescoreExecutionPlans) HandleSerialize(ctx context.Context, in middleware.SerializeInput, next middleware.SerializeHandler) (
	out middleware.SerializeOutput, metadata middleware.Metadata, err error,
) {
	_, span := tracing.StartSpan(ctx, "OperationSerializer")
	endTimer := startMetricTimer(ctx, "client.call.serialization_duration")
	defer endTimer()
	defer span.End()
	input, ok := in.Parameters.(*ListRescoreExecutionPlansInput)
	if !ok {
		return out, metadata, fmt.Errorf("unexpected input type %T", in.Parameters)
	}
	_ = input

	req, ok := in.Request.(*smithyhttp.Request)
	if !ok {
		return out, metadata, fmt.Errorf("unexpected transport type %T", in.Request)
	}

	req.Method = http.MethodPost
	req.URL.Path = "/service/AWSKendraRerankingFrontendService/operation/ListRescoreExecutionPlans"
	req.Header.Set("smithy-protocol", "rpc-v2-cbor")

	req.Header.Set("Content-Type", "application/cbor")
	req.Header.Set("Accept", "application/cbor")

	cv, err := serializeCBOR_ListRescoreExecutionPlansInput(input)
	if err != nil {
		return out, metadata, &smithy.SerializationError{Err: err}
	}

	payload := bytes.NewReader(smithycbor.Encode(cv))
	if req, err = req.SetStream(payload); err != nil {
		return out, metadata, &smithy.SerializationError{Err: err}
	}

	in.Request = req

	endTimer()
	span.End()

	return next.HandleSerialize(ctx, in)
}

type smithyRpcv2cbor_serializeOpListTagsForResource struct {
}

func (*smithyRpcv2cbor_serializeOpListTagsForResource) ID() string {
	return "OperationSerializer"
}

func (m *smithyRpcv2cbor_serializeOpListTagsForResource) HandleSerialize(ctx context.Context, in middleware.SerializeInput, next middleware.SerializeHandler) (
	out middleware.SerializeOutput, metadata middleware.Metadata, err error,
) {
	_, span := tracing.StartSpan(ctx, "OperationSerializer")
	endTimer := startMetricTimer(ctx, "client.call.serialization_duration")
	defer endTimer()
	defer span.End()
	input, ok := in.Parameters.(*ListTagsForResourceInput)
	if !ok {
		return out, metadata, fmt.Errorf("unexpected input type %T", in.Parameters)
	}
	_ = input

	req, ok := in.Request.(*smithyhttp.Request)
	if !ok {
		return out, metadata, fmt.Errorf("unexpected transport type %T", in.Request)
	}

	req.Method = http.MethodPost
	req.URL.Path = "/service/AWSKendraRerankingFrontendService/operation/ListTagsForResource"
	req.Header.Set("smithy-protocol", "rpc-v2-cbor")

	req.Header.Set("Content-Type", "application/cbor")
	req.Header.Set("Accept", "application/cbor")

	cv, err := serializeCBOR_ListTagsForResourceInput(input)
	if err != nil {
		return out, metadata, &smithy.SerializationError{Err: err}
	}

	payload := bytes.NewReader(smithycbor.Encode(cv))
	if req, err = req.SetStream(payload); err != nil {
		return out, metadata, &smithy.SerializationError{Err: err}
	}

	in.Request = req

	endTimer()
	span.End()

	return next.HandleSerialize(ctx, in)
}

type smithyRpcv2cbor_serializeOpRescore struct {
}

func (*smithyRpcv2cbor_serializeOpRescore) ID() string {
	return "OperationSerializer"
}

func (m *smithyRpcv2cbor_serializeOpRescore) HandleSerialize(ctx context.Context, in middleware.SerializeInput, next middleware.SerializeHandler) (
	out middleware.SerializeOutput, metadata middleware.Metadata, err error,
) {
	_, span := tracing.StartSpan(ctx, "OperationSerializer")
	endTimer := startMetricTimer(ctx, "client.call.serialization_duration")
	defer endTimer()
	defer span.End()
	input, ok := in.Parameters.(*RescoreInput)
	if !ok {
		return out, metadata, fmt.Errorf("unexpected input type %T", in.Parameters)
	}
	_ = input

	req, ok := in.Request.(*smithyhttp.Request)
	if !ok {
		return out, metadata, fmt.Errorf("unexpected transport type %T", in.Request)
	}

	req.Method = http.MethodPost
	req.URL.Path = "/service/AWSKendraRerankingFrontendService/operation/Rescore"
	req.Header.Set("smithy-protocol", "rpc-v2-cbor")

	req.Header.Set("Content-Type", "application/cbor")
	req.Header.Set("Accept", "application/cbor")

	cv, err := serializeCBOR_RescoreInput(input)
	if err != nil {
		return out, metadata, &smithy.SerializationError{Err: err}
	}

	payload := bytes.NewReader(smithycbor.Encode(cv))
	if req, err = req.SetStream(payload); err != nil {
		return out, metadata, &smithy.SerializationError{Err: err}
	}

	in.Request = req

	endTimer()
	span.End()

	return next.HandleSerialize(ctx, in)
}

type smithyRpcv2cbor_serializeOpTagResource struct {
}

func (*smithyRpcv2cbor_serializeOpTagResource) ID() string {
	return "OperationSerializer"
}

func (m *smithyRpcv2cbor_serializeOpTagResource) HandleSerialize(ctx context.Context, in middleware.SerializeInput, next middleware.SerializeHandler) (
	out middleware.SerializeOutput, metadata middleware.Metadata, err error,
) {
	_, span := tracing.StartSpan(ctx, "OperationSerializer")
	endTimer := startMetricTimer(ctx, "client.call.serialization_duration")
	defer endTimer()
	defer span.End()
	input, ok := in.Parameters.(*TagResourceInput)
	if !ok {
		return out, metadata, fmt.Errorf("unexpected input type %T", in.Parameters)
	}
	_ = input

	req, ok := in.Request.(*smithyhttp.Request)
	if !ok {
		return out, metadata, fmt.Errorf("unexpected transport type %T", in.Request)
	}

	req.Method = http.MethodPost
	req.URL.Path = "/service/AWSKendraRerankingFrontendService/operation/TagResource"
	req.Header.Set("smithy-protocol", "rpc-v2-cbor")

	req.Header.Set("Content-Type", "application/cbor")
	req.Header.Set("Accept", "application/cbor")

	cv, err := serializeCBOR_TagResourceInput(input)
	if err != nil {
		return out, metadata, &smithy.SerializationError{Err: err}
	}

	payload := bytes.NewReader(smithycbor.Encode(cv))
	if req, err = req.SetStream(payload); err != nil {
		return out, metadata, &smithy.SerializationError{Err: err}
	}

	in.Request = req

	endTimer()
	span.End()

	return next.HandleSerialize(ctx, in)
}

type smithyRpcv2cbor_serializeOpUntagResource struct {
}

func (*smithyRpcv2cbor_serializeOpUntagResource) ID() string {
	return "OperationSerializer"
}

func (m *smithyRpcv2cbor_serializeOpUntagResource) HandleSerialize(ctx context.Context, in middleware.SerializeInput, next middleware.SerializeHandler) (
	out middleware.SerializeOutput, metadata middleware.Metadata, err error,
) {
	_, span := tracing.StartSpan(ctx, "OperationSerializer")
	endTimer := startMetricTimer(ctx, "client.call.serialization_duration")
	defer endTimer()
	defer span.End()
	input, ok := in.Parameters.(*UntagResourceInput)
	if !ok {
		return out, metadata, fmt.Errorf("unexpected input type %T", in.Parameters)
	}
	_ = input

	req, ok := in.Request.(*smithyhttp.Request)
	if !ok {
		return out, metadata, fmt.Errorf("unexpected transport type %T", in.Request)
	}

	req.Method = http.MethodPost
	req.URL.Path = "/service/AWSKendraRerankingFrontendService/operation/UntagResource"
	req.Header.Set("smithy-protocol", "rpc-v2-cbor")

	req.Header.Set("Content-Type", "application/cbor")
	req.Header.Set("Accept", "application/cbor")

	cv, err := serializeCBOR_UntagResourceInput(input)
	if err != nil {
		return out, metadata, &smithy.SerializationError{Err: err}
	}

	payload := bytes.NewReader(smithycbor.Encode(cv))
	if req, err = req.SetStream(payload); err != nil {
		return out, metadata, &smithy.SerializationError{Err: err}
	}

	in.Request = req

	endTimer()
	span.End()

	return next.HandleSerialize(ctx, in)
}

type smithyRpcv2cbor_serializeOpUpdateRescoreExecutionPlan struct {
}

func (*smithyRpcv2cbor_serializeOpUpdateRescoreExecutionPlan) ID() string {
	return "OperationSerializer"
}

func (m *smithyRpcv2cbor_serializeOpUpdateRescoreExecutionPlan) HandleSerialize(ctx context.Context, in middleware.SerializeInput, next middleware.SerializeHandler) (
	out middleware.SerializeOutput, metadata middleware.Metadata, err error,
) {
	_, span := tracing.StartSpan(ctx, "OperationSerializer")
	endTimer := startMetricTimer(ctx, "client.call.serialization_duration")
	defer endTimer()
	defer span.End()
	input, ok := in.Parameters.(*UpdateRescoreExecutionPlanInput)
	if !ok {
		return out, metadata, fmt.Errorf("unexpected input type %T", in.Parameters)
	}
	_ = input

	req, ok := in.Request.(*smithyhttp.Request)
	if !ok {
		return out, metadata, fmt.Errorf("unexpected transport type %T", in.Request)
	}

	req.Method = http.MethodPost
	req.URL.Path = "/service/AWSKendraRerankingFrontendService/operation/UpdateRescoreExecutionPlan"
	req.Header.Set("smithy-protocol", "rpc-v2-cbor")

	req.Header.Set("Content-Type", "application/cbor")
	req.Header.Set("Accept", "application/cbor")

	cv, err := serializeCBOR_UpdateRescoreExecutionPlanInput(input)
	if err != nil {
		return out, metadata, &smithy.SerializationError{Err: err}
	}

	payload := bytes.NewReader(smithycbor.Encode(cv))
	if req, err = req.SetStream(payload); err != nil {
		return out, metadata, &smithy.SerializationError{Err: err}
	}

	in.Request = req

	endTimer()
	span.End()

	return next.HandleSerialize(ctx, in)
}
func serializeCBOR_BodyTokensList(v []string) (smithycbor.Value, error) {
	vl := smithycbor.List{}
	for i := range v {

		ser, err := serializeCBOR_String(v[i])
		if err != nil {
			return nil, err
		}
		vl = append(vl, ser)
	}
	return vl, nil
}

func serializeCBOR_CapacityUnitsConfiguration(v *types.CapacityUnitsConfiguration) (smithycbor.Value, error) {
	vm := smithycbor.Map{}
	if v.RescoreCapacityUnits != nil {
		ser, err := serializeCBOR_Int32(*v.RescoreCapacityUnits)
		if err != nil {
			return nil, err
		}
		vm["RescoreCapacityUnits"] = ser
	}
	return vm, nil
}

func serializeCBOR_Document(v *types.Document) (smithycbor.Value, error) {
	vm := smithycbor.Map{}
	if v.Id != nil {
		ser, err := serializeCBOR_String(*v.Id)
		if err != nil {
			return nil, err
		}
		vm["Id"] = ser
	}
	if v.GroupId != nil {
		ser, err := serializeCBOR_String(*v.GroupId)
		if err != nil {
			return nil, err
		}
		vm["GroupId"] = ser
	}
	if v.Title != nil {
		ser, err := serializeCBOR_String(*v.Title)
		if err != nil {
			return nil, err
		}
		vm["Title"] = ser
	}
	if v.Body != nil {
		ser, err := serializeCBOR_String(*v.Body)
		if err != nil {
			return nil, err
		}
		vm["Body"] = ser
	}
	if v.TokenizedTitle != nil {
		ser, err := serializeCBOR_TitleTokensList(v.TokenizedTitle)
		if err != nil {
			return nil, err
		}
		vm["TokenizedTitle"] = ser
	}
	if v.TokenizedBody != nil {
		ser, err := serializeCBOR_BodyTokensList(v.TokenizedBody)
		if err != nil {
			return nil, err
		}
		vm["TokenizedBody"] = ser
	}
	if v.OriginalScore != nil {
		ser, err := serializeCBOR_Float32(*v.OriginalScore)
		if err != nil {
			return nil, err
		}
		vm["OriginalScore"] = ser
	}
	return vm, nil
}

func serializeCBOR_DocumentList(v []types.Document) (smithycbor.Value, error) {
	vl := smithycbor.List{}
	for i := range v {

		ser, err := serializeCBOR_Document(&v[i])
		if err != nil {
			return nil, err
		}
		vl = append(vl, ser)
	}
	return vl, nil
}

func serializeCBOR_Tag(v *types.Tag) (smithycbor.Value, error) {
	vm := smithycbor.Map{}
	if v.Key != nil {
		ser, err := serializeCBOR_String(*v.Key)
		if err != nil {
			return nil, err
		}
		vm["Key"] = ser
	}
	if v.Value != nil {
		ser, err := serializeCBOR_String(*v.Value)
		if err != nil {
			return nil, err
		}
		vm["Value"] = ser
	}
	return vm, nil
}

func serializeCBOR_TagKeyList(v []string) (smithycbor.Value, error) {
	vl := smithycbor.List{}
	for i := range v {

		ser, err := serializeCBOR_String(v[i])
		if err != nil {
			return nil, err
		}
		vl = append(vl, ser)
	}
	return vl, nil
}

func serializeCBOR_TagList(v []types.Tag) (smithycbor.Value, error) {
	vl := smithycbor.List{}
	for i := range v {

		ser, err := serializeCBOR_Tag(&v[i])
		if err != nil {
			return nil, err
		}
		vl = append(vl, ser)
	}
	return vl, nil
}

func serializeCBOR_TitleTokensList(v []string) (smithycbor.Value, error) {
	vl := smithycbor.List{}
	for i := range v {

		ser, err := serializeCBOR_String(v[i])
		if err != nil {
			return nil, err
		}
		vl = append(vl, ser)
	}
	return vl, nil
}

func serializeCBOR_Float32(v float32) (smithycbor.Value, error) {
	return smithycbor.Float32(v), nil
}

func serializeCBOR_Int32(v int32) (smithycbor.Value, error) {
	if v < 0 {
		return smithycbor.NegInt(uint64(-v)), nil
	}
	return smithycbor.Uint(uint64(v)), nil
}

func serializeCBOR_String(v string) (smithycbor.Value, error) {
	return smithycbor.String(v), nil
}

func serializeCBOR_CreateRescoreExecutionPlanInput(v *CreateRescoreExecutionPlanInput) (smithycbor.Value, error) {
	vm := smithycbor.Map{}
	if v.Name != nil {
		ser, err := serializeCBOR_String(*v.Name)
		if err != nil {
			return nil, err
		}
		vm["Name"] = ser
	}
	if v.Description != nil {
		ser, err := serializeCBOR_String(*v.Description)
		if err != nil {
			return nil, err
		}
		vm["Description"] = ser
	}
	if v.CapacityUnits != nil {
		ser, err := serializeCBOR_CapacityUnitsConfiguration(v.CapacityUnits)
		if err != nil {
			return nil, err
		}
		vm["CapacityUnits"] = ser
	}
	if v.Tags != nil {
		ser, err := serializeCBOR_TagList(v.Tags)
		if err != nil {
			return nil, err
		}
		vm["Tags"] = ser
	}
	if v.ClientToken != nil {
		ser, err := serializeCBOR_String(*v.ClientToken)
		if err != nil {
			return nil, err
		}
		vm["ClientToken"] = ser
	}
	return vm, nil
}

func serializeCBOR_DeleteRescoreExecutionPlanInput(v *DeleteRescoreExecutionPlanInput) (smithycbor.Value, error) {
	vm := smithycbor.Map{}
	if v.Id != nil {
		ser, err := serializeCBOR_String(*v.Id)
		if err != nil {
			return nil, err
		}
		vm["Id"] = ser
	}
	return vm, nil
}

func serializeCBOR_DescribeRescoreExecutionPlanInput(v *DescribeRescoreExecutionPlanInput) (smithycbor.Value, error) {
	vm := smithycbor.Map{}
	if v.Id != nil {
		ser, err := serializeCBOR_String(*v.Id)
		if err != nil {
			return nil, err
		}
		vm["Id"] = ser
	}
	return vm, nil
}

func serializeCBOR_ListRescoreExecutionPlansInput(v *ListRescoreExecutionPlansInput) (smithycbor.Value, error) {
	vm := smithycbor.Map{}
	if v.NextToken != nil {
		ser, err := serializeCBOR_String(*v.NextToken)
		if err != nil {
			return nil, err
		}
		vm["NextToken"] = ser
	}
	if v.MaxResults != nil {
		ser, err := serializeCBOR_Int32(*v.MaxResults)
		if err != nil {
			return nil, err
		}
		vm["MaxResults"] = ser
	}
	return vm, nil
}

func serializeCBOR_ListTagsForResourceInput(v *ListTagsForResourceInput) (smithycbor.Value, error) {
	vm := smithycbor.Map{}
	if v.ResourceARN != nil {
		ser, err := serializeCBOR_String(*v.ResourceARN)
		if err != nil {
			return nil, err
		}
		vm["ResourceARN"] = ser
	}
	return vm, nil
}

func serializeCBOR_RescoreInput(v *RescoreInput) (smithycbor.Value, error) {
	vm := smithycbor.Map{}
	if v.RescoreExecutionPlanId != nil {
		ser, err := serializeCBOR_String(*v.RescoreExecutionPlanId)
		if err != nil {
			return nil, err
		}
		vm["RescoreExecutionPlanId"] = ser
	}
	if v.SearchQuery != nil {
		ser, err := serializeCBOR_String(*v.SearchQuery)
		if err != nil {
			return nil, err
		}
		vm["SearchQuery"] = ser
	}
	if v.Documents != nil {
		ser, err := serializeCBOR_DocumentList(v.Documents)
		if err != nil {
			return nil, err
		}
		vm["Documents"] = ser
	}
	return vm, nil
}

func serializeCBOR_TagResourceInput(v *TagResourceInput) (smithycbor.Value, error) {
	vm := smithycbor.Map{}
	if v.ResourceARN != nil {
		ser, err := serializeCBOR_String(*v.ResourceARN)
		if err != nil {
			return nil, err
		}
		vm["ResourceARN"] = ser
	}
	if v.Tags != nil {
		ser, err := serializeCBOR_TagList(v.Tags)
		if err != nil {
			return nil, err
		}
		vm["Tags"] = ser
	}
	return vm, nil
}

func serializeCBOR_UntagResourceInput(v *UntagResourceInput) (smithycbor.Value, error) {
	vm := smithycbor.Map{}
	if v.ResourceARN != nil {
		ser, err := serializeCBOR_String(*v.ResourceARN)
		if err != nil {
			return nil, err
		}
		vm["ResourceARN"] = ser
	}
	if v.TagKeys != nil {
		ser, err := serializeCBOR_TagKeyList(v.TagKeys)
		if err != nil {
			return nil, err
		}
		vm["TagKeys"] = ser
	}
	return vm, nil
}

func serializeCBOR_UpdateRescoreExecutionPlanInput(v *UpdateRescoreExecutionPlanInput) (smithycbor.Value, error) {
	vm := smithycbor.Map{}
	if v.Id != nil {
		ser, err := serializeCBOR_String(*v.Id)
		if err != nil {
			return nil, err
		}
		vm["Id"] = ser
	}
	if v.Name != nil {
		ser, err := serializeCBOR_String(*v.Name)
		if err != nil {
			return nil, err
		}
		vm["Name"] = ser
	}
	if v.Description != nil {
		ser, err := serializeCBOR_String(*v.Description)
		if err != nil {
			return nil, err
		}
		vm["Description"] = ser
	}
	if v.CapacityUnits != nil {
		ser, err := serializeCBOR_CapacityUnitsConfiguration(v.CapacityUnits)
		if err != nil {
			return nil, err
		}
		vm["CapacityUnits"] = ser
	}
	return vm, nil
}
